---
title: "ANOVA Within DAT Across Quantile Levels"
author: "Aaron J. DeSalvio"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, message=FALSE, warning=FALSE}
library(lubridate)
library(lme4)
library(lmerTest)
library(ggplot2)
library(dplyr)
library(tidyr)
library(data.table)
```

# Analysis of Variance - AM5 & HM5

These ANOVA models quantify the extent of a Genotype × Quantile interaction at each time point (measured in days after transplanting, DAT).

```{r cars}
# Note - the distributional data files are too large to be stored on GitHub. Once you download them, save them to their own directory and replace the value of data_path_server with that path.
# Replace data_path with the folder location where you downloaded all other data related to the repository.
# You can optionally specify a path to save RData when the loop completes one round of processing ANOVAs for all DATs associated with a specific vegetation index.

data_path <- 'D:/Users/aaron.desalvio/My Drive/TAMU/Murray Lab/Writing/Manuscripts/2025_Distributional_Data/CS24_Cotton/0.0_Data/'
data_path_server <- '//murray_lab/FLIGHTS2/Processed2/Texas/CS24/MULTI/CS24-STEL/Data_Products/Individual_VIs/'
RData_path <- 'C:/Users/aaron.desalvio/Downloads/Temp_RData/'
csvs <- list.files(path = data_path_server, pattern = '\\.csv$')
all_vis <- lapply(strsplit(as.character(csvs), '-'), '[', 6) %>% unlist()

# We will change the csvs vector to only contain one element to reduce the duration of producing this RMarkdown file. If you'd like to run the entire loop with all VIs, comment out the next line.
csvs <- csvs[1]

# We'll also only run a few DATs (time points) to speed up processing of this file. If you'd like to run the entire analysis, first comment out the next line, and then UNCOMMENT the line of code marked with # UNCOMMENT HERE below.
dat.loop <- c(107, 108, 109)
```

# Loop to run ANOVA models with Genotype × Quantile interaction at all time points

```{r ANOVA loop, message=FALSE, warning=FALSE}
# Initialize empty lists to store results
G_list <- list()
VC_list <- list()

for (i in 1:length(csvs)) {
  
  current_vi <- all_vis[i]
  print(paste('Current VI:', current_vi))
  
  # Read data from CSV files
  print(paste('Loading VI data frame for', current_vi))
  df <- fread(paste0(data_path_server, 'CS24-STEL-MULTI-RTK-Distributions-', current_vi, '-FieldCoords.csv')) %>% as.data.frame() %>% arrange(DAT)
  print(paste0('VI data frame loaded for ', current_vi, '!'))
  
  # Remove low-quality DATs
  DATs_exclude <- c(46, 71:72, 99:100)
  df <- df %>% filter(!DAT %in% DATs_exclude)
  
  # Remove plant that died early in the season
  df <- df %>% filter(!Row_Range == '413_15')
  
  # Basic plot for inspection of data
  sort(unique(df$DAT))
  df.plot <- df %>% filter(Pedigree == 5016, DAT == 140)
  plot(df.plot$probability, df.plot$quantile)
  
  # DAT vector for loop
  # dat.loop <- sort(unique(df$DAT)) # UNCOMMENT HERE
  
  # Loop over each environment
  for (dat in dat.loop) {
    
    # Subset data for the current DAT
    df.subset <- df[df$DAT == dat, ]
    
    # Convert variables to appropriate data types
    df.subset$Range <- as.factor(df.subset$Range)
    df.subset$Row <- as.factor(df.subset$Row)
    df.subset$Replicate <- as.factor(df.subset$Replicate)
    df.subset$Pedigree <- as.factor(df.subset$Pedigree)
    df.subset$probability <- as.factor(df.subset$probability)
    
    # Progress report
    print(paste('ANOVA Model:', 'DAT', dat, 'VI', current_vi))
    
    # Fit the linear mixed-effects model after setting "Inf" and NaN as NA
    response <- df.subset$quantile
    response[is.na(response) | response == 'Inf' | is.nan(response) | response == '-Inf'] <- NA
    
    anova <- lmer(response ~
                    (1 | Pedigree) +
                    (1 | probability) +
                    (1 | Pedigree:probability) +
                    (1 | Range:probability) +
                    (1 | Row:probability) +
                    (1 | Replicate:probability),
                  data = df.subset)
    
    # Calculate RMSE
    rmse_value <- sqrt(mean(residuals(anova)^2))
    
    # Calculate R-squared
    R <- MuMIn::r.squaredGLMM(anova)[, "R2c"]  # Conditional R-squared
    
    # Extract variance components
    VC <- as.data.frame(VarCorr(anova))
    VC$Percent <- round(VC$vcov / sum(VC$vcov) * 100, 2)
    
    # Calculate heritability
    nRep <- length(unique(df.subset$Replicate))
    nProb <- length(unique(df.subset$probability))
    Vg <- VC[VC$grp == "Pedigree", "vcov"]
    Vgp <- VC[VC$grp == "Pedigree:probability", "vcov"]
    Ve <- VC[VC$grp == "Residual", "vcov"]
    #heritability <- Vg / (Vg + (Vgp / nProb) + (Ve / (nRep * nProb)))
    #heritability <- round(heritability, 3)
    heritability <- Vg / (Vg + (Vgp) + (Ve / (nRep)))
    heritability <- round(heritability, 3)
    
    # Add additional information to VC data frame
    VC$Rmse <- rmse_value
    VC$Heritability <- heritability
    VC$R_squared <- R
    VC$Vegetation.Index <- current_vi
    VC$DAT <- dat
    print(VC)
    
    # Store VC in the list
    VC_list[[paste(dat, current_vi, sep = '_')]] <- VC
    
    # Extract random effects for 'Pedigree'
    G <- coef(anova)$Pedigree
    G$Pedigree <- rownames(G)
    
    # Store G in the list
    G_list[[paste(dat, current_vi, sep = '_')]] <- G
    
  }
  # Save RData for current loop iteration
  save.image(paste0(RData_path, 'ANOVA_Within_DAT_Across_Quantile_', current_vi, '.RData'))
}
```

## Save the ANOVA results

```{r Save the ANOVA results}
G_df <- do.call(rbind, G_list)
VC_df <- do.call(rbind, VC_list)

# View the first few rows of the results
head(G_df)
head(VC_df)

# Data wrangling before exporting
VC_df_cols <- colnames(VC_df)
VC_df_cols <- VC_df_cols[!VC_df_cols %in% c('var1', 'var2')]
VC_df <- VC_df[,VC_df_cols]
VC_df$DAT_Prob_VI <- rownames(VC_df)

colnames(G_df)[1] <- 'BLUP'
G_df$DAT_VI.Pedigree <- rownames(G_df)
G_df$VI.Pedigree <- lapply(strsplit(as.character(G_df$DAT_VI.Pedigree), '_'), '[', 2) %>% unlist()
G_df$Vegetation.Index <- lapply(strsplit(as.character(G_df$VI.Pedigree), '\\.'), '[', 1)

# Save the data frames
#fwrite(VC_df, paste0(data_path, 'VarComp_Within_DAT_Across_Quantile_Revised_Herit.csv'))
#fwrite(G_df, paste0(data_path, 'Quantile_BLUPs_Within_DAT_Across_Quantile_Revised_Herit.csv'))
```